### ISSUE TITLE
Missing dependency?

### ISSUE THREAD

**Issue by bbaassssiiee** [bcoca/ansible-selenium-role#3]
It seems a dependency is missing in my VM: update-alternatives: not found

NOTIFIED: [briancoca.selenium | selenium_started] ***************************** 
<192.168.10.20> state=started enabled=yes name=selenium_standalone
failed: [client] => {"failed": true}
msg: /etc/init.d/selenium_standalone: 54: /etc/init.d/selenium_standalone: /usr/sbin/update-alternatives: not found
/etc/init.d/selenium_standalone: 54: /etc/init.d/selenium_standalone: /usr/sbin/update-alternatives: not found
start-stop-daemon: warning: this system is not able to track process names
longer than 15 characters, please use --exec instead of --name.

**Comment by bbaassssiiee** [comment]
It is actually a PATH issue, update-alternatives lives in /usr/bin here.

Kudos to: https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=720575

**Comment by bcoca** [comment]
closing as this should be fixed by merge of #4
